# Generated by Django 2.0 on 2019-03-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, default='All', max_length=50, null=True)),
                ('lease_options', models.CharField(max_length=250)),
                ('garage', models.IntegerField()),
                ('furnished', models.CharField(max_length=20)),
                ('reference', models.IntegerField()),
            ],
        ),
    ]
