# Generated by Django 2.0 on 2019-03-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='houses/%Y/%m/%d/'),
        ),
    ]
