# Generated by Django 2.0 on 2019-03-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_house_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('For Rent', 'FOR RENT'), ('For Sale', 'FOR SALE')], default='All', max_length=25),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
